### ISSUE TITLE
Create admin page for configuring home page sections

### ISSUE THREAD

**Issue by sandriu** [CatalinFrancu/dignitas#107]
We need a new admin page for configuring the text displayed on home page without using hardcoded text. **Also note that home page for anonymous visitors should be different than home page for logged in users.**

This admin page should help configure the following home page sections:

- one big section that explains _**What is Dignitas**_ as a website (not everybody knows what is a fact checking website); the admin page should contain fields for completing a [hero section](https://getbootstrap.com/2.3.2/examples/hero.html) with:

- [ ] one heading
- [ ] one paragraph
- [ ] 1-2 buttons for exploring the detailed description

- one big section ("the detailed description") that explains **_how Dignitas works_**; usually 5 steps (visually identical) would be enough; each step would have the following fields:

- [ ] one heading
- [ ] one paragraph
- [ ] one button to navigate to another page or section within home page
- [ ] one image.

**Comment by CatalinFrancu** [comment]
- [ ] create a static_resource table with fields for name and language
- [ ] support creating / deleting static resources
- [ ] support basic editing for text resources (HTML, JS, CSS)
- [ ] add support for static resources to `Smart.php`
