### ISSUE TITLE
Move 'Add statement' button to the rest of entity actions

### ISSUE THREAD

**Issue by sandriu** [CatalinFrancu/dignitas#115]
On Entity page:
![Viorica_Dăncilă_Dignitas](https://user-images.githubusercontent.com/1265882/82049146-88206b00-96be-11ea-80f4-9e32f06c2190.png)

**Comment by sandriu** [comment]
The rationale behind this move is that for popular authors, there will be so many statements that the 'Add statement' button will never be visible without a lot of scrolling on page. 
The 'Add statement' button isn't very related to the rest of possible actions for an author page, but it's still the main desired action for any author (aka primary action on page).

**Comment by CatalinFrancu** [comment]
Will do. I only put it there because of #79, but I agree it makes more sense next to the other buttons.

**Comment by sandriu** [comment]
I know. I changed my mind meanwhile :D .
