### ISSUE TITLE
Hamburger menu icon not visible

### ISSUE THREAD

**Issue by sandriu** [CatalinFrancu/dignitas#118]
The code exists, the icon is missing, see top left corner from header.
It's about the "menu" icon from Fontello.

![bug_hamburger_menu_icon_missing](https://user-images.githubusercontent.com/1265882/82700272-89c9d000-9c76-11ea-8a1c-d3b6d98c59c3.png)

**Comment by CatalinFrancu** [comment]
I blame [this](https://github.com/CatalinFrancu/dignitas/commit/4a4e1e99f7ea5da3122457a7a8f2d56eff6b1e30#diff-5c4747cfd3651e61c30ccc6bda001509). :-) I looked at the Bootstrap CSS and, for the menu icon to appear, it wants a `.navbar-light` or `.navbar-dark` class on the navbar. I will put back the `.navbar-light` class, which almost works. It adds a discreet gray border around the buttons. I think that is fine, but let me know if it's not.

**Comment by CatalinFrancu** [comment]
Fixed in 6a6a6a9825e6baceda4413cf4dc974ac3b11bc06
