### ISSUE TITLE
Fix the animations and layout for header menus

### ISSUE THREAD

**Issue by sandriu** [CatalinFrancu/dignitas#56]
The header for all pages should contain: 
- left menu: search box + global menu icon (collapsed both on desktop and mobile)
- website logo, centered between left menu and right menu
- right menu: language menu + user menu.

- [x] Both menus should appear from the margin they're attached to. And disappear in the same direction.
- [x] Both menus should have full height of the page.
- [ ] On mobile, the search box should be placed on its own row, below the standard navbar with collapsed menus and logo.

**Comment by CatalinFrancu** [comment]
We decided to leave the search box where it is.

Dropdown menus don't play nice with the `.bg-dark` Bootstrap class. TODO: remove these classes and change the Bootstrap color scheme using Sass.
