### ISSUE TITLE
Call-to-action on Entity page

### ISSUE THREAD

**Issue by sandriu** [CatalinFrancu/dignitas#79]
My current proposal would be to add a blank card with a button for adding a new statement, in order to encourage adding more statements per entity. Below is a possible layout:

![Entity-page-CTA](https://user-images.githubusercontent.com/1265882/76079875-54ceab00-5fae-11ea-8d32-3902f496d750.png)

**Comment by CatalinFrancu** [comment]
Can do. :-) I will code it once we integrate the new entity page layout.
