### ISSUE TITLE
Load custom fonts

### ISSUE THREAD

**Issue by sandriu** [CatalinFrancu/dignitas#81]
Open Sans: Regular 400 & Regular 400 Italic & Bold 700 via https://fonts.google.com/specimen/Open+Sans?subset=latin-ext&preview.text=%C4%83%C3%A2%C8%99%C8%9B%C3%AE+%C4%82%C3%82%C8%98%C8%9A%C3%8E+a%C3%A2%C3%A2&preview.text_type=custom&query=open+san&selection.family=Open+Sans:ital,wght@0,400;0,700;1,400&sidebar.open

Spartan: Regular 400 & Medium 500 via https://fonts.google.com/specimen/Spartan?subset=latin-ext&preview.text=%C4%83%C3%A2%C8%99%C8%9B%C3%AE+%C4%82%C3%82%C8%98%C8%9A%C3%8E+a%C3%A2%C3%A2&preview.text_type=custom&selection.family=Spartan:wght@400;500

**Comment by CatalinFrancu** [comment]
Note to self: get WOFF2 versions using https://google-webfonts-helper.herokuapp.com/

**Comment by CatalinFrancu** [comment]
Oops! Reopening because the diacritics look wrong (look at the **ă**). We should probably choose something else instead of Spartan.

![diacritics](https://user-images.githubusercontent.com/1180392/76395148-5964dc00-637f-11ea-96ad-7b354d0b5b31.png)

**Comment by CatalinFrancu** [comment]
Oops again -- I just need to fetch the Latin-ext glyphs as well. My bad.

**Comment by sandriu** [comment]
All proposed fonts are/were already tested for diacritics.
